services:
  discovery-b:
    build: ../../discovery
    network_mode: host
    environment:
      - STACK_ID=stack-b
      - VNI=1000
      - MULTICAST_GROUP=239.1.1.1
      - DISCOVERY_PORT=4790
      - ANNOUNCE_INTERVAL=30
      - PEER_TIMEOUT=90
    volumes:
      - discovery-data-b:/var/lib/docker-router
    restart: unless-stopped

  router-b:
    image: docker-router:latest
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    environment:
      - STACK_ID=stack-b
      - CONFIG_FILE=/etc/router/routing.yaml
    volumes:
      - discovery-data-b:/var/lib/docker-router:ro
      - ../../router/config/routing-stack-b.yaml:/etc/router/routing.yaml:ro
    networks:
      - internal
    depends_on:
      - discovery-b
    restart: unless-stopped

  test-b:
    image: alpine:latest
    command: |
      sh -c "
        apk add --no-cache curl iputils
        echo 'Stack B Service Started'
        while true; do
          echo '=== Stack B Network Status ==='
          echo 'My IP:'
          ip addr show eth0 | grep 'inet ' | awk '{print \$2}'
          echo 'Routing table:'
          ip route | grep -E '(172\.|192\.168\.100\.)'
          echo 'Discovery peers:'
          if [ -f /shared/discovery.json ]; then
            cat /shared/discovery.json | grep -A 5 'stack_id' | head -20
          else
            echo 'No discovery data'
          fi
          echo '================================'
          sleep 60
        done
      "
    volumes:
      - discovery-data-b:/shared:ro
    networks:
      - internal
    depends_on:
      - router-b

volumes:
  discovery-data-b:

networks:
  internal:
    name: stack-b-internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.21.0.0/16