version: '3.8'

configs:
  routing-config:
    content: |
      version: 1
      stack_id: stack-c
      vni: 1000
      vxlan_subnet: 10.1.1.0/24
      local_vxlan_ip: 10.1.1.4
      container_subnet: 172.22.0.0/16
      
      stack_mappings:
        stack-a:
          vxlan_ip: 10.1.1.2
          container_subnet: 172.30.0.0/16
        stack-b:
          vxlan_ip: 10.1.1.3
          container_subnet: 172.31.0.0/16
        stack-c:
          vxlan_ip: 10.1.1.4
          container_subnet: 172.22.0.0/16
  
  discovery-config:
    content: |
      {
        "version": 1,
        "last_update": "2025-07-16T12:00:00Z",
        "peers": [
          {
            "stack_id": "stack-a",
            "host_ip": "192.168.200.3",
            "vxlan_endpoint": "192.168.200.3:4789",
            "vni": 1000,
            "last_seen": "2025-07-16T12:00:00Z",
            "status": "active"
          },
          {
            "stack_id": "stack-b",
            "host_ip": "192.168.200.142",
            "vxlan_endpoint": "192.168.200.142:4789",
            "vni": 1000,
            "last_seen": "2025-07-16T12:00:00Z",
            "status": "active"
          }
        ]
      }

services:
  router:
    image: docker-router:latest
    network_mode: host
    privileged: true
    environment:
      - STACK_ID=stack-c
      - VNI=1000
      - VXLAN_SUBNET=10.1.1.0/24
      - LOCAL_VXLAN_IP=10.1.1.4
      - CONFIG_FILE=/etc/router/routing.yaml
    configs:
      - source: routing-config
        target: /etc/router/routing.yaml
      - source: discovery-config
        target: /var/lib/docker-router/discovery.json
    restart: unless-stopped

  app:
    image: nginx:alpine
    networks:
      - internal
    depends_on:
      - router
    ports:
      - "8080:80"

networks:
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.22.0.0/16
          gateway: 172.22.0.1