services:
  discovery-c:
    build: ../../discovery
    network_mode: host
    environment:
      - STACK_ID=stack-c
      - VNI=1000
      - MULTICAST_GROUP=239.1.1.1
      - DISCOVERY_PORT=4790
      - ANNOUNCE_INTERVAL=30
      - PEER_TIMEOUT=90
    volumes:
      - discovery-data-c:/var/lib/docker-router
    restart: unless-stopped

  router-c:
    image: docker-router:latest
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    privileged: true
    environment:
      - STACK_ID=stack-c
      - CONFIG_FILE=/etc/router/routing.yaml
    volumes:
      - discovery-data-c:/var/lib/docker-router:ro
    configs:
      - source: routing-config-c
        target: /etc/router/routing.yaml
    networks:
      - internal
    depends_on:
      - discovery-c
    restart: unless-stopped

  test-c:
    image: alpine:latest
    command: |
      sh -c "
        apk add --no-cache curl iputils
        echo 'Stack C Service Started'
        while true; do
          echo '=== Stack C Network Status ==='
          echo 'My IP:'
          ip addr show eth0 | grep 'inet ' | awk '{print \$2}'
          echo 'Routing table:'
          ip route | grep -E '(172\.|192\.168\.100\.)'
          echo 'Discovery peers:'
          if [ -f /shared/discovery.json ]; then
            cat /shared/discovery.json | grep -A 5 'stack_id' | head -20
          else
            echo 'No discovery data'
          fi
          echo '================================'
          sleep 60
        done
      "
    volumes:
      - discovery-data-c:/shared:ro
    networks:
      - internal
    depends_on:
      - router-c

volumes:
  discovery-data-c:

networks:
  internal:
    name: stack-c-internal
    driver: bridge
    ipam:
      config:
        - subnet: 172.26.0.0/16

configs:
  routing-config-c:
    content: |
      version: 1
      stack_id: stack-c
      vni: 1000
      vxlan_subnet: 192.168.100.0/24
      local_vxlan_ip: 192.168.100.3
      container_subnet: 172.26.0.0/16

      stack_mappings:
        stack-a:
          vxlan_ip: 192.168.100.1
          container_subnet: 172.20.0.0/16
        stack-b:
          vxlan_ip: 192.168.100.2
          container_subnet: 172.21.0.0/16
        stack-c:
          vxlan_ip: 192.168.100.3
          container_subnet: 172.26.0.0/16
        stack-d:
          vxlan_ip: 192.168.100.4
          container_subnet: 172.23.0.0/16